---
- name: Fixup kubelet client cert rotation 1/2
  lineinfile:
    path: "{{ kube_config_dir }}/kubelet.conf"
    regexp: '^    client-certificate-data: '
    line: '    client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem'
    backup: yes
  notify:
    - "Master | reload kubelet"
  when:
    - not ansible_check_mode

- name: Fixup kubelet client cert rotation 2/2
  lineinfile:
    path: "{{ kube_config_dir }}/kubelet.conf"
    regexp: '^    client-key-data: '
    line: '    client-key: /var/lib/kubelet/pki/kubelet-client-current.pem'
    backup: yes
  notify:
    - "Master | reload kubelet"
  when:
    - not ansible_check_mode
